/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createServerRootRoute } from '@tanstack/react-start/server'

import { Route as rootRouteImport } from './routes/__root'
import { Route as TutorRouteImport } from './routes/tutor'
import { Route as OverviewRouteImport } from './routes/overview'
import { Route as DataRouteImport } from './routes/data'
import { Route as Tutor_idIndexRouteImport } from './routes/$tutor_id/index'
import { Route as Tutor_idTutorRouteImport } from './routes/$tutor_id/tutor'
import { ServerRoute as ApiHealthServerRouteImport } from './routes/api/health'

const rootServerRouteImport = createServerRootRoute()

const TutorRoute = TutorRouteImport.update({
  id: '/tutor',
  path: '/tutor',
  getParentRoute: () => rootRouteImport,
} as any)
const OverviewRoute = OverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => rootRouteImport,
} as any)
const DataRoute = DataRouteImport.update({
  id: '/data',
  path: '/data',
  getParentRoute: () => rootRouteImport,
} as any)
const Tutor_idIndexRoute = Tutor_idIndexRouteImport.update({
  id: '/$tutor_id/',
  path: '/$tutor_id/',
  getParentRoute: () => rootRouteImport,
} as any)
const Tutor_idTutorRoute = Tutor_idTutorRouteImport.update({
  id: '/$tutor_id/tutor',
  path: '/$tutor_id/tutor',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthServerRoute = ApiHealthServerRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootServerRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/data': typeof DataRoute
  '/overview': typeof OverviewRoute
  '/tutor': typeof TutorRoute
  '/$tutor_id/tutor': typeof Tutor_idTutorRoute
  '/$tutor_id': typeof Tutor_idIndexRoute
}
export interface FileRoutesByTo {
  '/data': typeof DataRoute
  '/overview': typeof OverviewRoute
  '/tutor': typeof TutorRoute
  '/$tutor_id/tutor': typeof Tutor_idTutorRoute
  '/$tutor_id': typeof Tutor_idIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/data': typeof DataRoute
  '/overview': typeof OverviewRoute
  '/tutor': typeof TutorRoute
  '/$tutor_id/tutor': typeof Tutor_idTutorRoute
  '/$tutor_id/': typeof Tutor_idIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/data'
    | '/overview'
    | '/tutor'
    | '/$tutor_id/tutor'
    | '/$tutor_id'
  fileRoutesByTo: FileRoutesByTo
  to: '/data' | '/overview' | '/tutor' | '/$tutor_id/tutor' | '/$tutor_id'
  id:
    | '__root__'
    | '/data'
    | '/overview'
    | '/tutor'
    | '/$tutor_id/tutor'
    | '/$tutor_id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  DataRoute: typeof DataRoute
  OverviewRoute: typeof OverviewRoute
  TutorRoute: typeof TutorRoute
  Tutor_idTutorRoute: typeof Tutor_idTutorRoute
  Tutor_idIndexRoute: typeof Tutor_idIndexRoute
}
export interface FileServerRoutesByFullPath {
  '/api/health': typeof ApiHealthServerRoute
}
export interface FileServerRoutesByTo {
  '/api/health': typeof ApiHealthServerRoute
}
export interface FileServerRoutesById {
  __root__: typeof rootServerRouteImport
  '/api/health': typeof ApiHealthServerRoute
}
export interface FileServerRouteTypes {
  fileServerRoutesByFullPath: FileServerRoutesByFullPath
  fullPaths: '/api/health'
  fileServerRoutesByTo: FileServerRoutesByTo
  to: '/api/health'
  id: '__root__' | '/api/health'
  fileServerRoutesById: FileServerRoutesById
}
export interface RootServerRouteChildren {
  ApiHealthServerRoute: typeof ApiHealthServerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tutor': {
      id: '/tutor'
      path: '/tutor'
      fullPath: '/tutor'
      preLoaderRoute: typeof TutorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/overview': {
      id: '/overview'
      path: '/overview'
      fullPath: '/overview'
      preLoaderRoute: typeof OverviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data': {
      id: '/data'
      path: '/data'
      fullPath: '/data'
      preLoaderRoute: typeof DataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$tutor_id/': {
      id: '/$tutor_id/'
      path: '/$tutor_id'
      fullPath: '/$tutor_id'
      preLoaderRoute: typeof Tutor_idIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$tutor_id/tutor': {
      id: '/$tutor_id/tutor'
      path: '/$tutor_id/tutor'
      fullPath: '/$tutor_id/tutor'
      preLoaderRoute: typeof Tutor_idTutorRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}
declare module '@tanstack/react-start/server' {
  interface ServerFileRoutesByPath {
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  DataRoute: DataRoute,
  OverviewRoute: OverviewRoute,
  TutorRoute: TutorRoute,
  Tutor_idTutorRoute: Tutor_idTutorRoute,
  Tutor_idIndexRoute: Tutor_idIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
const rootServerRouteChildren: RootServerRouteChildren = {
  ApiHealthServerRoute: ApiHealthServerRoute,
}
export const serverRouteTree = rootServerRouteImport
  ._addFileChildren(rootServerRouteChildren)
  ._addFileTypes<FileServerRouteTypes>()
