/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TutorRouteImport } from './routes/tutor'
import { Route as TestRouteImport } from './routes/test'
import { Route as OverviewRouteImport } from './routes/overview'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DataRouteImport } from './routes/data'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as Tutor_idIndexRouteImport } from './routes/$tutor_id/index'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as AdminImportRouteImport } from './routes/admin/import'
import { Route as AdminCreateRouteImport } from './routes/admin/create'
import { Route as AdminTutorIdRouteImport } from './routes/admin/$tutorId'
import { Route as Tutor_idTutorRouteImport } from './routes/$tutor_id/tutor'
import { Route as AdminUsersRouteRouteImport } from './routes/admin/users/route'
import { Route as AdminUsersIndexRouteImport } from './routes/admin/users/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AdminUsersCreateRouteImport } from './routes/admin/users/create'
import { Route as AdminUsersUserIdRouteImport } from './routes/admin/users/$userId'

const TutorRoute = TutorRouteImport.update({
  id: '/tutor',
  path: '/tutor',
  getParentRoute: () => rootRouteImport,
} as any)
const TestRoute = TestRouteImport.update({
  id: '/test',
  path: '/test',
  getParentRoute: () => rootRouteImport,
} as any)
const OverviewRoute = OverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DataRoute = DataRouteImport.update({
  id: '/data',
  path: '/data',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const Tutor_idIndexRoute = Tutor_idIndexRouteImport.update({
  id: '/$tutor_id/',
  path: '/$tutor_id/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminImportRoute = AdminImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminCreateRoute = AdminCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminTutorIdRoute = AdminTutorIdRouteImport.update({
  id: '/$tutorId',
  path: '/$tutorId',
  getParentRoute: () => AdminRouteRoute,
} as any)
const Tutor_idTutorRoute = Tutor_idTutorRouteImport.update({
  id: '/$tutor_id/tutor',
  path: '/$tutor_id/tutor',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRouteRoute = AdminUsersRouteRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminUsersIndexRoute = AdminUsersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminUsersRouteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersCreateRoute = AdminUsersCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => AdminUsersRouteRoute,
} as any)
const AdminUsersUserIdRoute = AdminUsersUserIdRouteImport.update({
  id: '/$userId',
  path: '/$userId',
  getParentRoute: () => AdminUsersRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/admin': typeof AdminRouteRouteWithChildren
  '/data': typeof DataRoute
  '/login': typeof LoginRoute
  '/overview': typeof OverviewRoute
  '/test': typeof TestRoute
  '/tutor': typeof TutorRoute
  '/admin/users': typeof AdminUsersRouteRouteWithChildren
  '/$tutor_id/tutor': typeof Tutor_idTutorRoute
  '/admin/$tutorId': typeof AdminTutorIdRoute
  '/admin/create': typeof AdminCreateRoute
  '/admin/import': typeof AdminImportRoute
  '/api/chat': typeof ApiChatRoute
  '/api/health': typeof ApiHealthRoute
  '/$tutor_id/': typeof Tutor_idIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/users/$userId': typeof AdminUsersUserIdRoute
  '/admin/users/create': typeof AdminUsersCreateRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/admin/users/': typeof AdminUsersIndexRoute
}
export interface FileRoutesByTo {
  '/data': typeof DataRoute
  '/login': typeof LoginRoute
  '/overview': typeof OverviewRoute
  '/test': typeof TestRoute
  '/tutor': typeof TutorRoute
  '/$tutor_id/tutor': typeof Tutor_idTutorRoute
  '/admin/$tutorId': typeof AdminTutorIdRoute
  '/admin/create': typeof AdminCreateRoute
  '/admin/import': typeof AdminImportRoute
  '/api/chat': typeof ApiChatRoute
  '/api/health': typeof ApiHealthRoute
  '/$tutor_id': typeof Tutor_idIndexRoute
  '/admin': typeof AdminIndexRoute
  '/admin/users/$userId': typeof AdminUsersUserIdRoute
  '/admin/users/create': typeof AdminUsersCreateRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/admin/users': typeof AdminUsersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/admin': typeof AdminRouteRouteWithChildren
  '/data': typeof DataRoute
  '/login': typeof LoginRoute
  '/overview': typeof OverviewRoute
  '/test': typeof TestRoute
  '/tutor': typeof TutorRoute
  '/admin/users': typeof AdminUsersRouteRouteWithChildren
  '/$tutor_id/tutor': typeof Tutor_idTutorRoute
  '/admin/$tutorId': typeof AdminTutorIdRoute
  '/admin/create': typeof AdminCreateRoute
  '/admin/import': typeof AdminImportRoute
  '/api/chat': typeof ApiChatRoute
  '/api/health': typeof ApiHealthRoute
  '/$tutor_id/': typeof Tutor_idIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/users/$userId': typeof AdminUsersUserIdRoute
  '/admin/users/create': typeof AdminUsersCreateRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/admin/users/': typeof AdminUsersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/admin'
    | '/data'
    | '/login'
    | '/overview'
    | '/test'
    | '/tutor'
    | '/admin/users'
    | '/$tutor_id/tutor'
    | '/admin/$tutorId'
    | '/admin/create'
    | '/admin/import'
    | '/api/chat'
    | '/api/health'
    | '/$tutor_id/'
    | '/admin/'
    | '/admin/users/$userId'
    | '/admin/users/create'
    | '/api/auth/$'
    | '/admin/users/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/data'
    | '/login'
    | '/overview'
    | '/test'
    | '/tutor'
    | '/$tutor_id/tutor'
    | '/admin/$tutorId'
    | '/admin/create'
    | '/admin/import'
    | '/api/chat'
    | '/api/health'
    | '/$tutor_id'
    | '/admin'
    | '/admin/users/$userId'
    | '/admin/users/create'
    | '/api/auth/$'
    | '/admin/users'
  id:
    | '__root__'
    | '/admin'
    | '/data'
    | '/login'
    | '/overview'
    | '/test'
    | '/tutor'
    | '/admin/users'
    | '/$tutor_id/tutor'
    | '/admin/$tutorId'
    | '/admin/create'
    | '/admin/import'
    | '/api/chat'
    | '/api/health'
    | '/$tutor_id/'
    | '/admin/'
    | '/admin/users/$userId'
    | '/admin/users/create'
    | '/api/auth/$'
    | '/admin/users/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  DataRoute: typeof DataRoute
  LoginRoute: typeof LoginRoute
  OverviewRoute: typeof OverviewRoute
  TestRoute: typeof TestRoute
  TutorRoute: typeof TutorRoute
  Tutor_idTutorRoute: typeof Tutor_idTutorRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiHealthRoute: typeof ApiHealthRoute
  Tutor_idIndexRoute: typeof Tutor_idIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tutor': {
      id: '/tutor'
      path: '/tutor'
      fullPath: '/tutor'
      preLoaderRoute: typeof TutorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test': {
      id: '/test'
      path: '/test'
      fullPath: '/test'
      preLoaderRoute: typeof TestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/overview': {
      id: '/overview'
      path: '/overview'
      fullPath: '/overview'
      preLoaderRoute: typeof OverviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data': {
      id: '/data'
      path: '/data'
      fullPath: '/data'
      preLoaderRoute: typeof DataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/$tutor_id/': {
      id: '/$tutor_id/'
      path: '/$tutor_id'
      fullPath: '/$tutor_id/'
      preLoaderRoute: typeof Tutor_idIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/import': {
      id: '/admin/import'
      path: '/import'
      fullPath: '/admin/import'
      preLoaderRoute: typeof AdminImportRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/create': {
      id: '/admin/create'
      path: '/create'
      fullPath: '/admin/create'
      preLoaderRoute: typeof AdminCreateRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/$tutorId': {
      id: '/admin/$tutorId'
      path: '/$tutorId'
      fullPath: '/admin/$tutorId'
      preLoaderRoute: typeof AdminTutorIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/$tutor_id/tutor': {
      id: '/$tutor_id/tutor'
      path: '/$tutor_id/tutor'
      fullPath: '/$tutor_id/tutor'
      preLoaderRoute: typeof Tutor_idTutorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/users/': {
      id: '/admin/users/'
      path: '/'
      fullPath: '/admin/users/'
      preLoaderRoute: typeof AdminUsersIndexRouteImport
      parentRoute: typeof AdminUsersRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users/create': {
      id: '/admin/users/create'
      path: '/create'
      fullPath: '/admin/users/create'
      preLoaderRoute: typeof AdminUsersCreateRouteImport
      parentRoute: typeof AdminUsersRouteRoute
    }
    '/admin/users/$userId': {
      id: '/admin/users/$userId'
      path: '/$userId'
      fullPath: '/admin/users/$userId'
      preLoaderRoute: typeof AdminUsersUserIdRouteImport
      parentRoute: typeof AdminUsersRouteRoute
    }
  }
}

interface AdminUsersRouteRouteChildren {
  AdminUsersUserIdRoute: typeof AdminUsersUserIdRoute
  AdminUsersCreateRoute: typeof AdminUsersCreateRoute
  AdminUsersIndexRoute: typeof AdminUsersIndexRoute
}

const AdminUsersRouteRouteChildren: AdminUsersRouteRouteChildren = {
  AdminUsersUserIdRoute: AdminUsersUserIdRoute,
  AdminUsersCreateRoute: AdminUsersCreateRoute,
  AdminUsersIndexRoute: AdminUsersIndexRoute,
}

const AdminUsersRouteRouteWithChildren = AdminUsersRouteRoute._addFileChildren(
  AdminUsersRouteRouteChildren,
)

interface AdminRouteRouteChildren {
  AdminUsersRouteRoute: typeof AdminUsersRouteRouteWithChildren
  AdminTutorIdRoute: typeof AdminTutorIdRoute
  AdminCreateRoute: typeof AdminCreateRoute
  AdminImportRoute: typeof AdminImportRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminUsersRouteRoute: AdminUsersRouteRouteWithChildren,
  AdminTutorIdRoute: AdminTutorIdRoute,
  AdminCreateRoute: AdminCreateRoute,
  AdminImportRoute: AdminImportRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AdminRouteRoute: AdminRouteRouteWithChildren,
  DataRoute: DataRoute,
  LoginRoute: LoginRoute,
  OverviewRoute: OverviewRoute,
  TestRoute: TestRoute,
  TutorRoute: TutorRoute,
  Tutor_idTutorRoute: Tutor_idTutorRoute,
  ApiChatRoute: ApiChatRoute,
  ApiHealthRoute: ApiHealthRoute,
  Tutor_idIndexRoute: Tutor_idIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
